### ISSUE TITLE
OverflowError in scap_to_svg.py

### ISSUE THREAD

**Issue by pressureless** [squidrice21/StripMaker#3]
Given a `.svg` file, I can use `svg_to_scap_width_exact.py` to convert it into a `.scap` file.

For the attached file, I can still correctly convert the `.scap` back to a `.svg` file by `scap_to_svg.py`. However, it will crash when running `run_prediction.py`. 

<img width="786" alt="image" src="https://github.com/squidrice21/StripMaker/assets/8511053/db0ee294-05c3-492c-8340-ae52ee36f126">

![demo](https://github.com/squidrice21/StripMaker/assets/8511053/59137e6c-b60e-4e5d-9848-c99ee7542fac)

**Comment by pressureless** [comment]
Resolved. Path error.

**Comment by pressureless** [comment]
Error remains for some files

**Comment by squidrice21** [comment]
Can you send me a file with the remaining issues? And can you give me more details?

**Comment by pressureless** [comment]
Here's an example.
[demo.zip](https://github.com/squidrice21/StripMaker/files/14068422/demo.zip)

I converted `.svg` to `.scap` using `python ./visualization/svg_to_scap_width_exact.py path/to/svg -o path/to/scap`, then set the path of `.scap` in `inputs_test.yml`, finally ran `python3 ./python/launching/run_prediction.py ./data/inputs_test.yml --exe [build_folder]/clustering-solve,[build_folder]/clustering-endend --output ./snapshot/stripmaker_test.pdf --spiral`
